2014/03/13 13:10:36 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/
---
2014/03/13 13:10:59 [error] [exception.CException] exception 'CException' with message 'Путь CAssetManager.basePath "/Users/work/Sites/yiibps/assets" задан неверно. Удостоверьтесь, что директория существует и доступна для записи пользователю, под которым запущен веб-сервер.' in /Users/work/Sites/yiibps/framework/web/CAssetManager.php:138
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CAssetManager.php(123): CAssetManager->setBasePath('/Users/work/Sit...')
#1 /Users/work/Sites/yiibps/framework/web/CAssetManager.php(217): CAssetManager->getBasePath()
#2 /Users/work/Sites/yiibps/framework/gii/GiiModule.php(143): CAssetManager->publish('/Users/work/Sit...')
#3 /Users/work/Sites/yiibps/framework/base/CComponent.php(111): GiiModule->getAssetsUrl()
#4 /Users/work/Sites/yiibps/framework/base/CModule.php(105): CComponent->__get('assetsUrl')
#5 /Users/work/Sites/yiibps/framework/gii/views/layouts/main.php(5): CModule->__get('assetsUrl')
#6 /Users/work/Sites/yiibps/framework/web/CBaseController.php(126): require('/Users/work/Sit...')
#7 /Users/work/Sites/yiibps/framework/web/CBaseController.php(95): CBaseController->renderInternal('/Users/work/Sit...', Array, true)
#8 /Users/work/Sites/yiibps/framework/web/widgets/CContentDecorator.php(76): CBaseController->renderFile('/Users/work/Sit...', Array, true)
#9 /Users/work/Sites/yiibps/framework/web/widgets/CContentDecorator.php(54): CContentDecorator->decorate('<div class="con...')
#10 /Users/work/Sites/yiibps/framework/web/widgets/COutputProcessor.php(44): CContentDecorator->processOutput('<div class="con...')
#11 /Users/work/Sites/yiibps/framework/web/CBaseController.php(206): COutputProcessor->run()
#12 /Users/work/Sites/yiibps/framework/web/CBaseController.php(300): CBaseController->endWidget('CContentDecorat...')
#13 /Users/work/Sites/yiibps/framework/gii/views/layouts/column1.php(7): CBaseController->endContent()
#14 /Users/work/Sites/yiibps/framework/web/CBaseController.php(126): require('/Users/work/Sit...')
#15 /Users/work/Sites/yiibps/framework/web/CBaseController.php(95): CBaseController->renderInternal('/Users/work/Sit...', Array, true)
#16 /Users/work/Sites/yiibps/framework/web/CController.php(784): CBaseController->renderFile('/Users/work/Sit...', Array, true)
#17 /Users/work/Sites/yiibps/framework/gii/controllers/DefaultController.php(17): CController->render('index')
#18 /Users/work/Sites/yiibps/framework/web/actions/CInlineAction.php(49): DefaultController->actionIndex()
#19 /Users/work/Sites/yiibps/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#20 /Users/work/Sites/yiibps/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#21 /Users/work/Sites/yiibps/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#22 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(282): CController->run('')
#23 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#24 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#25 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#26 {main}
REQUEST_URI=/index.php?r=gii
---
2014/03/13 13:18:45 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "view".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('view')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=view
---
2014/03/13 13:22:22 [error] [exception.CException] exception 'CException' with message 'Псевдоним "application.modules.menu.widgets.menuWidget" неверен. Убедитесь, что он указывает на существующий PHP файл.' in /Users/work/Sites/yiibps/framework/YiiBase.php:322
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWidgetFactory.php(146): YiiBase::import('application.mod...', true)
#1 /Users/work/Sites/yiibps/framework/web/CBaseController.php(146): CWidgetFactory->createWidget(Object(MainController), 'application.mod...', Array)
#2 /Users/work/Sites/yiibps/framework/web/CBaseController.php(172): CBaseController->createWidget('application.mod...', Array)
#3 /Users/work/Sites/yiibps/protected/views/layouts/main.php(15): CBaseController->widget('application.mod...', Array)
#4 /Users/work/Sites/yiibps/framework/web/CBaseController.php(126): require('/Users/work/Sit...')
#5 /Users/work/Sites/yiibps/framework/web/CBaseController.php(95): CBaseController->renderInternal('/Users/work/Sit...', Array, true)
#6 /Users/work/Sites/yiibps/framework/web/widgets/CContentDecorator.php(76): CBaseController->renderFile('/Users/work/Sit...', Array, true)
#7 /Users/work/Sites/yiibps/framework/web/widgets/CContentDecorator.php(54): CContentDecorator->decorate('    <div id="co...')
#8 /Users/work/Sites/yiibps/framework/web/widgets/COutputProcessor.php(44): CContentDecorator->processOutput('    <div id="co...')
#9 /Users/work/Sites/yiibps/framework/web/CBaseController.php(206): COutputProcessor->run()
#10 /Users/work/Sites/yiibps/framework/web/CBaseController.php(300): CBaseController->endWidget('CContentDecorat...')
#11 /Users/work/Sites/yiibps/protected/views/layouts/column1.php(6): CBaseController->endContent()
#12 /Users/work/Sites/yiibps/framework/web/CBaseController.php(126): require('/Users/work/Sit...')
#13 /Users/work/Sites/yiibps/framework/web/CBaseController.php(95): CBaseController->renderInternal('/Users/work/Sit...', Array, true)
#14 /Users/work/Sites/yiibps/framework/web/CController.php(784): CBaseController->renderFile('/Users/work/Sit...', Array, true)
#15 /Users/work/Sites/yiibps/protected/controllers/MainController.php(7): CController->render('index')
#16 /Users/work/Sites/yiibps/framework/web/actions/CInlineAction.php(49): MainController->actionIndex()
#17 /Users/work/Sites/yiibps/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#18 /Users/work/Sites/yiibps/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#19 /Users/work/Sites/yiibps/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#20 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(282): CController->run('')
#21 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('')
#22 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#23 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#24 {main}
REQUEST_URI=/index.php
---
2014/03/13 13:31:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "gii".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=gii
---
2014/03/13 15:46:28 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 15:56:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 15:56:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 15:56:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 15:56:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 15:56:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 15:56:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 15:56:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 15:56:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 15:56:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 15:56:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 15:56:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 15:56:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 15:56:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 15:56:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 15:56:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 15:56:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 15:56:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 15:56:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 15:56:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 15:56:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 15:56:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 15:56:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 15:56:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 15:56:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 15:56:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 15:56:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 15:56:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 15:56:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 15:56:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 15:56:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 15:56:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 15:56:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 15:56:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 15:56:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 15:56:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 15:56:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 15:56:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 15:56:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 15:56:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 15:56:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 15:56:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 15:57:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 15:57:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 15:57:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 15:57:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 15:57:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 15:57:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 15:57:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 15:57:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 15:57:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 15:57:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 15:57:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 15:57:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 15:57:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 15:57:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 15:57:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 15:57:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 15:57:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 15:57:35 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 15:57:35 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 15:57:35 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 15:57:35 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 15:57:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 15:57:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 15:57:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 15:57:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 15:57:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 15:57:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 15:57:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 15:57:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 15:57:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 15:57:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 15:57:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 15:57:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 15:57:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 15:57:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 15:57:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 15:57:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 15:57:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 15:57:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 15:57:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 15:57:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 16:10:18 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 16:10:18 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 16:10:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 16:10:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 16:10:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 16:10:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 16:10:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 16:10:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 16:10:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 16:10:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 16:10:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 16:10:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 16:10:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 16:10:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 16:10:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 16:10:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 16:10:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 16:10:22 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 16:10:22 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 16:10:22 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 16:10:22 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 16:10:56 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 16:10:56 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 16:10:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 16:10:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 16:10:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 16:10:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 16:10:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 16:10:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 16:10:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 16:10:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 16:10:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 16:10:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 16:10:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 16:10:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 16:10:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 16:10:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 16:10:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 16:10:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 16:10:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 16:10:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 16:28:06 [error] [php] Indirect modification of overloaded property User::$attributes has no effect (/Users/work/Sites/yiibps/protected/controllers/UserController.php:73)
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/filters/CFilterChain.php(133): UserController->runAction()
#1 /Users/work/Sites/yiibps/framework/web/filters/CFilter.php(40): CFilterChain->run()
#2 /Users/work/Sites/yiibps/framework/web/CController.php(1145): CAccessControlFilter->filter()
#3 /Users/work/Sites/yiibps/framework/web/filters/CInlineFilter.php(58): UserController->filterAccessControl()
#4 /Users/work/Sites/yiibps/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter()
#5 /Users/work/Sites/yiibps/framework/web/CController.php(291): CFilterChain->run()
#6 /Users/work/Sites/yiibps/framework/web/CController.php(265): UserController->runActionWithFilters()
#7 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(282): UserController->run()
#8 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController()
#9 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#10 /Users/work/Sites/yiibps/admin.php(13): CWebApplication->run()
REQUEST_URI=/admin.php?r=user/create
in /Users/work/Sites/yiibps/protected/controllers/UserController.php (73)
in /Users/work/Sites/yiibps/admin.php (13)
2014/03/13 16:30:33 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'У вас недостаточно прав для выполнения указанного действия.' in /Users/work/Sites/yiibps/framework/web/auth/CAccessControlFilter.php:182
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/auth/CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), '?? ?????? ?????...')
#1 /Users/work/Sites/yiibps/framework/web/filters/CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 /Users/work/Sites/yiibps/framework/web/CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 /Users/work/Sites/yiibps/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 /Users/work/Sites/yiibps/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 /Users/work/Sites/yiibps/framework/web/CController.php(291): CFilterChain->run()
#6 /Users/work/Sites/yiibps/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(282): CController->run('admin')
#8 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('user/admin')
#9 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#10 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/admin.php?r=user/admin
HTTP_REFERER=http://yiibps/admin.php?r=user/create
---
2014/03/13 16:30:53 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'У вас недостаточно прав для выполнения указанного действия.' in /Users/work/Sites/yiibps/framework/web/auth/CAccessControlFilter.php:182
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/auth/CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), '?? ?????? ?????...')
#1 /Users/work/Sites/yiibps/framework/web/filters/CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 /Users/work/Sites/yiibps/framework/web/CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 /Users/work/Sites/yiibps/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 /Users/work/Sites/yiibps/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 /Users/work/Sites/yiibps/framework/web/CController.php(291): CFilterChain->run()
#6 /Users/work/Sites/yiibps/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(282): CController->run('')
#8 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('')
#9 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#10 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/admin.php
---
2014/03/13 16:30:57 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'У вас недостаточно прав для выполнения указанного действия.' in /Users/work/Sites/yiibps/framework/web/auth/CAccessControlFilter.php:182
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/auth/CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), '?? ?????? ?????...')
#1 /Users/work/Sites/yiibps/framework/web/filters/CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 /Users/work/Sites/yiibps/framework/web/CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 /Users/work/Sites/yiibps/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 /Users/work/Sites/yiibps/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 /Users/work/Sites/yiibps/framework/web/CController.php(291): CFilterChain->run()
#6 /Users/work/Sites/yiibps/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(282): CController->run('')
#8 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('')
#9 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#10 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/admin.php
---
2014/03/13 16:34:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "page/".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('page/')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=page/
---
2014/03/13 16:34:59 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "page/".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('page/')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=page/
---
2014/03/13 16:35:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "page/".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('page/')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=page/
---
2014/03/13 16:36:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "page/".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('page/')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=page/
---
2014/03/13 16:36:50 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "page/".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('page/')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=page/
---
2014/03/13 16:37:04 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "page/".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('page/')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=page/
---
2014/03/13 16:42:16 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'У вас недостаточно прав для выполнения указанного действия.' in /Users/work/Sites/yiibps/framework/web/auth/CAccessControlFilter.php:182
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/auth/CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), '?? ?????? ?????...')
#1 /Users/work/Sites/yiibps/framework/web/filters/CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 /Users/work/Sites/yiibps/framework/web/CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 /Users/work/Sites/yiibps/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 /Users/work/Sites/yiibps/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 /Users/work/Sites/yiibps/framework/web/CController.php(291): CFilterChain->run()
#6 /Users/work/Sites/yiibps/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(282): CController->run('')
#8 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('')
#9 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#10 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/admin.php
---
2014/03/13 16:43:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "page/".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('page/')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=page/
---
2014/03/13 16:43:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "page/".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('page/')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=page/
---
2014/03/13 16:43:31 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "page/Page".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('page/Page')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=page/Page
---
2014/03/13 16:45:11 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "page/Page".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('page/Page')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=page/Page
---
2014/03/13 16:46:15 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "page/Page".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('page/Page')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=page/Page
---
2014/03/13 16:49:43 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'У вас недостаточно прав для выполнения указанного действия.' in /Users/work/Sites/yiibps/framework/web/auth/CAccessControlFilter.php:182
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/auth/CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), '?? ?????? ?????...')
#1 /Users/work/Sites/yiibps/framework/web/filters/CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 /Users/work/Sites/yiibps/framework/web/CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 /Users/work/Sites/yiibps/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 /Users/work/Sites/yiibps/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 /Users/work/Sites/yiibps/framework/web/CController.php(291): CFilterChain->run()
#6 /Users/work/Sites/yiibps/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(282): CController->run('logout')
#8 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('admin/logout')
#9 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#10 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/admin.php?r=admin/logout
---
2014/03/13 16:50:11 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'У вас недостаточно прав для выполнения указанного действия.' in /Users/work/Sites/yiibps/framework/web/auth/CAccessControlFilter.php:182
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/auth/CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), '?? ?????? ?????...')
#1 /Users/work/Sites/yiibps/framework/web/filters/CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 /Users/work/Sites/yiibps/framework/web/CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 /Users/work/Sites/yiibps/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 /Users/work/Sites/yiibps/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 /Users/work/Sites/yiibps/framework/web/CController.php(291): CFilterChain->run()
#6 /Users/work/Sites/yiibps/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(282): CController->run('Logout')
#8 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('admin/Logout')
#9 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#10 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/admin.php?r=admin/Logout
---
2014/03/13 16:52:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/logout".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/logout')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/logout
HTTP_REFERER=http://yiibps/admin.php
---
2014/03/13 16:53:14 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'У вас недостаточно прав для выполнения указанного действия.' in /Users/work/Sites/yiibps/framework/web/auth/CAccessControlFilter.php:182
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/auth/CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), '?? ?????? ?????...')
#1 /Users/work/Sites/yiibps/framework/web/filters/CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 /Users/work/Sites/yiibps/framework/web/CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 /Users/work/Sites/yiibps/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 /Users/work/Sites/yiibps/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 /Users/work/Sites/yiibps/framework/web/CController.php(291): CFilterChain->run()
#6 /Users/work/Sites/yiibps/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(282): CController->run('logout')
#8 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('admin/logout')
#9 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#10 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/admin.php?r=admin/logout
HTTP_REFERER=http://yiibps/admin.php
---
2014/03/13 16:54:20 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'У вас недостаточно прав для выполнения указанного действия.' in /Users/work/Sites/yiibps/framework/web/auth/CAccessControlFilter.php:182
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/auth/CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), '?? ?????? ?????...')
#1 /Users/work/Sites/yiibps/framework/web/filters/CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 /Users/work/Sites/yiibps/framework/web/CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 /Users/work/Sites/yiibps/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 /Users/work/Sites/yiibps/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 /Users/work/Sites/yiibps/framework/web/CController.php(291): CFilterChain->run()
#6 /Users/work/Sites/yiibps/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(282): CController->run('logout')
#8 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('admin/logout')
#9 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#10 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/admin.php?r=admin/logout
HTTP_REFERER=http://yiibps/admin.php
---
2014/03/13 17:18:16 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'У вас недостаточно прав для выполнения указанного действия.' in /Users/work/Sites/yiibps/framework/web/auth/CAccessControlFilter.php:182
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/auth/CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), '?? ?????? ?????...')
#1 /Users/work/Sites/yiibps/framework/web/filters/CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 /Users/work/Sites/yiibps/framework/web/CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 /Users/work/Sites/yiibps/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 /Users/work/Sites/yiibps/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 /Users/work/Sites/yiibps/framework/web/CController.php(291): CFilterChain->run()
#6 /Users/work/Sites/yiibps/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(282): CController->run('admin')
#8 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('page/admin')
#9 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#10 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/admin.php?r=page/admin
HTTP_REFERER=http://yiibps/admin.php?r=page
---
2014/03/13 17:33:05 [error] [exception.CException] exception 'CException' with message 'Не определено свойство "Page.update_date".' in /Users/work/Sites/yiibps/framework/base/CComponent.php:130
Stack trace:
#0 /Users/work/Sites/yiibps/framework/db/ar/CActiveRecord.php(145): CComponent->__get('update_date')
#1 /Users/work/Sites/yiibps/framework/validators/CDefaultValueValidator.php(44): CActiveRecord->__get('update_date')
#2 /Users/work/Sites/yiibps/framework/validators/CValidator.php(213): CDefaultValueValidator->validateAttribute(Object(Page), 'update_date')
#3 /Users/work/Sites/yiibps/framework/base/CModel.php(159): CValidator->validate(Object(Page), NULL)
#4 /Users/work/Sites/yiibps/framework/db/ar/CActiveRecord.php(805): CModel->validate(NULL)
#5 /Users/work/Sites/yiibps/protected/controllers/PageController.php(73): CActiveRecord->save()
#6 /Users/work/Sites/yiibps/framework/web/actions/CInlineAction.php(49): PageController->actionCreate()
#7 /Users/work/Sites/yiibps/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#8 /Users/work/Sites/yiibps/framework/web/filters/CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#9 /Users/work/Sites/yiibps/framework/web/filters/CFilter.php(40): CFilterChain->run()
#10 /Users/work/Sites/yiibps/framework/web/CController.php(1145): CFilter->filter(Object(CFilterChain))
#11 /Users/work/Sites/yiibps/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#12 /Users/work/Sites/yiibps/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#13 /Users/work/Sites/yiibps/framework/web/CController.php(291): CFilterChain->run()
#14 /Users/work/Sites/yiibps/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#15 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(282): CController->run('create')
#16 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('page/create')
#17 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#18 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#19 {main}
REQUEST_URI=/admin.php?r=page/create
HTTP_REFERER=http://yiibps/admin.php?r=page/create
---
2014/03/13 17:37:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
HTTP_REFERER=http://yiibps/index.php?r=page
---
2014/03/13 17:37:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
HTTP_REFERER=http://yiibps/index.php?r=page
---
2014/03/13 17:37:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
HTTP_REFERER=http://yiibps/index.php?r=page
---
2014/03/13 17:37:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
HTTP_REFERER=http://yiibps/index.php?r=page
---
2014/03/13 17:37:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
HTTP_REFERER=http://yiibps/index.php?r=page
---
2014/03/13 17:37:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
HTTP_REFERER=http://yiibps/index.php?r=page
---
2014/03/13 17:37:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
HTTP_REFERER=http://yiibps/index.php?r=page
---
2014/03/13 17:37:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
HTTP_REFERER=http://yiibps/index.php?r=page
---
2014/03/13 17:37:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
HTTP_REFERER=http://yiibps/index.php?r=page
---
2014/03/13 17:37:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
HTTP_REFERER=http://yiibps/index.php?r=page
---
2014/03/13 17:37:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
HTTP_REFERER=http://yiibps/index.php?r=page
---
2014/03/13 17:37:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
HTTP_REFERER=http://yiibps/index.php?r=page
---
2014/03/13 17:37:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
HTTP_REFERER=http://yiibps/index.php?r=page
---
2014/03/13 17:37:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
HTTP_REFERER=http://yiibps/index.php?r=page
---
2014/03/13 17:37:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
HTTP_REFERER=http://yiibps/index.php?r=page
---
2014/03/13 17:37:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
HTTP_REFERER=http://yiibps/index.php?r=page
---
2014/03/13 17:37:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
HTTP_REFERER=http://yiibps/index.php?r=page
---
2014/03/13 17:37:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
HTTP_REFERER=http://yiibps/index.php?r=page
---
2014/03/13 17:37:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
HTTP_REFERER=http://yiibps/index.php?r=page
---
2014/03/13 17:37:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
HTTP_REFERER=http://yiibps/index.php?r=page
---
2014/03/13 17:37:36 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 17:37:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 17:37:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 17:37:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 17:37:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 17:37:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 17:37:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 17:37:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 17:37:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 17:37:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 17:37:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 17:37:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 17:37:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 17:37:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 17:37:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 17:37:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 17:37:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 17:37:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 17:37:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 17:37:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 17:37:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 17:37:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 17:37:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 17:37:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 17:37:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 17:37:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 17:37:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 17:37:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 17:37:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 17:37:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 17:37:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 17:37:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 17:37:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 17:37:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 17:37:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 17:37:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 17:37:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 17:37:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 17:37:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 17:37:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 18:05:51 [error] [php] include(AdminController.php): failed to open stream: No such file or directory (/Users/work/Sites/yiibps/framework/YiiBase.php:427)
Stack trace:
#0 /Users/work/Sites/yiibps/protected/controllers/PageController.php(4): spl_autoload_call()
#1 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(354): require()
#2 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(276): CWebApplication->createController()
#3 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController()
#4 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#5 /Users/work/Sites/yiibps/index.php(13): CWebApplication->run()
REQUEST_URI=/index.php?r=page
in /Users/work/Sites/yiibps/protected/controllers/PageController.php (4)
in /Users/work/Sites/yiibps/index.php (13)
2014/03/13 18:06:00 [error] [php] include(AdminController.php): failed to open stream: No such file or directory (/Users/work/Sites/yiibps/framework/YiiBase.php:427)
Stack trace:
#0 /Users/work/Sites/yiibps/protected/controllers/PageController.php(4): spl_autoload_call()
#1 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(354): require()
#2 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(276): CWebApplication->createController()
#3 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController()
#4 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#5 /Users/work/Sites/yiibps/admin.php(13): CWebApplication->run()
REQUEST_URI=/admin.php?r=page
in /Users/work/Sites/yiibps/protected/controllers/PageController.php (4)
in /Users/work/Sites/yiibps/admin.php (13)
2014/03/13 18:06:05 [error] [php] include(AdminController.php): failed to open stream: No such file or directory (/Users/work/Sites/yiibps/framework/YiiBase.php:427)
Stack trace:
#0 /Users/work/Sites/yiibps/protected/controllers/PageController.php(4): spl_autoload_call()
#1 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(354): require()
#2 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(276): CWebApplication->createController()
#3 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController()
#4 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#5 /Users/work/Sites/yiibps/admin.php(13): CWebApplication->run()
REQUEST_URI=/admin.php?r=page/
in /Users/work/Sites/yiibps/protected/controllers/PageController.php (4)
in /Users/work/Sites/yiibps/admin.php (13)
2014/03/13 18:12:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 18:12:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 18:12:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 18:12:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 18:12:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 18:12:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 18:12:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 18:12:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 18:12:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 18:12:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 18:12:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 18:12:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 18:12:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 18:12:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 18:12:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 18:12:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 18:12:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 18:12:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 18:12:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 18:12:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 18:12:49 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/admin.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/admin.php?r=site/login
---
2014/03/13 18:13:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 18:13:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 18:13:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 18:13:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 18:13:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 18:13:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 18:13:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 18:13:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 18:13:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 18:13:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 18:13:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 18:13:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 18:13:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 18:13:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 18:13:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 18:13:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 18:13:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 18:13:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 18:13:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 18:13:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 18:13:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 18:13:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 18:13:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 18:13:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 18:13:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 18:13:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 18:13:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 18:13:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 18:13:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 18:13:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 18:13:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 18:13:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 18:13:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 18:13:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 18:13:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 18:13:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 18:13:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 18:13:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 18:13:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 18:13:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 18:13:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 18:14:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 18:14:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 18:14:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 18:14:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 18:14:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 18:14:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 18:14:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 18:14:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 18:14:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 18:14:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 18:14:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 18:14:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 18:14:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 18:14:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 18:14:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 18:14:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 18:14:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 18:14:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 18:14:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
2014/03/13 18:14:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "site/login".' in /Users/work/Sites/yiibps/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/work/Sites/yiibps/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /Users/work/Sites/yiibps/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Users/work/Sites/yiibps/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=site/login
---
